### PR TITLE
Use AkubraLowLevel special ID converter for Managed datastreams

### LINKED ISSUE #6: Can't find datastream
Testing this out on a subset of URIs I have hit one where it can't find the DC datastream.

Error log says
```
INFO 2018-05-30 10:27:48.123 [pool-2-thread-1] (ObjectProcessor) Operating on object URI: info:fedora/uofm:2939588
ERROR 2018-05-30 10:27:48.138 [pool-2-thread-1] (ObjectProcessor) Couldn't find datastream DC from object info:fedora/uofm:2939588! Caused by:
org.akubraproject.MissingBlobException: (Missing blob with id = 'file:0f/uofm%3A2939588%2BDC%2BDC.0')
        at org.akubraproject.fs.FSBlob.openInputStream(FSBlob.java:100)
        at org.akubraproject.impl.BlobWrapper.openInputStream(BlobWrapper.java:93)
        at edu.si.fcrepo.ObjectProcessor.getDatastreamContent(ObjectProcessor.java:205)
        at edu.si.fcrepo.ObjectProcessor.consume(ObjectProcessor.java:180)
        at edu.si.fcrepo.ObjectProcessor.accept(ObjectProcessor.java:152)
        at edu.si.fcrepo.Extract.lambda$null$3(Extract.java:240)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
INFO 2018-05-30 10:27:48.169 [main] (Extract) Reached 101 objects at end of objects with 0 in-queue after 1 errors.
INFO 2018-05-30 10:27:48.169 [main] (Extract) Finished extraction.
```
The file does not exist in the **0f** directory, nor does it exist there with the name **info%3Afedora%2Fuofm%3A2939588%2BDC%2BDC.0**. There is a managed DC datastream that I can access via Fedora. 0

I'll generate a new list of random pids to test with.

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #6 

This needs review and probably some sort of test, but it resolves the issue for me when my DC datastreams are Managed instead of Inline Xml.

### CODE REVIEW

**Comment by whikloj** [comment]
I knew Codecov would throw a fit, @ajs6f once you have a chance to look at this and provide some feedback I can add some unit testing for the `AkubraIDConverter`. Integration tests seem like they would be tougher based on what I can understand of your setup.

File: src/test/java/edu/si/fcrepo/AkubraIDConverterTest.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import org.mockito.junit.MockitoJUnitRunner;
+
+import static edu.si.fcrepo.AkubraIDConverter.FEDORA_URI;
+
+/**
+ * AkubraIDConverter unit tests
+ *
+ * @author whikloj
+ */
+@RunWith(MockitoJUnitRunner.class)
```
Comment (ajs6f) [inline src/test/java/edu/si/fcrepo/AkubraIDConverterTest.java]: I don't see any mocking going on-- do we need this runner?

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+                    throw new IllegalArgumentException("Unsupported encoding", e);
+                }
+            }
+        } catch (final URISyntaxException e) {
+            throw new IllegalArgumentException(
+                    "Malformed object or datastream token: " + token, e);
+        }
+    }
+
+    private static String uriEncode(final String s) throws UnsupportedEncodingException {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: Catch the `UnsupportedEncodingException` inside this method, because we know it will never be thrown, and drop the `try-catch` above.

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+ * Original code authored by Chris Wilper
+ *
+ * @author whikloj
+ */
+public class AkubraIDConverter {
+
+    /**
+     * Rather than bring in the entire PID class to get a string.
+     */
+    public static String FEDORA_URI = "info:fedora/";
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: This isn't used elsewhere, so `private static final`.

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+import java.net.URISyntaxException;
+import java.net.URLEncoder;
+
+/**
+ * Utility functions extracted/modified based on org.fcrepo.server.storage.lowlevel.akubra.AkubraLowLevelStorage.
+ * Original code authored by Chris Wilper
+ *
+ * @author whikloj
+ */
+public class AkubraIDConverter {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: Instead of a new class with `public static` methods, let's just put this jazz into `ObjectProcessor`.

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+            final int i = token.indexOf('+');
+            if (i == -1) {
+                if (token.startsWith(FEDORA_URI)) {
+                    // We have the namespace so we're good.
+                    return new URI(token);
+                }
+                // Just prepend the namespace
+                return new URI(FEDORA_URI + token);
+            } else {
+                final String[] dsParts = token.substring(i + 1).split("\\+");
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: Another in-line comment or two would be helpful here (through the end of this `else`). Under most circumstances it wouldn't matter, but this code is working with data produced by an EOL codebase the writers of which have long since moved on, so the more explicitness, the better.

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java [hunk 6]
```diff
@@ -0,0 +1,107 @@
...
+     *
+     * @param token the token to convert.
+     * @return the blob id.
+     * @throws IllegalArgumentException if the token is not a well-formed pid or datastream token.
+     */
+    public static URI getBlobId(final String token) {
+        try {
+            final int i = token.indexOf('+');
+            if (i == -1) {
+                if (token.startsWith(FEDORA_URI)) {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: I'm still a bit weirded out by this. Do you have any theory as to how your repo ended up with URIs lacking the prefix? I can't remember ever having seen that before.

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java [hunk 7]
```diff
@@ -0,0 +1,107 @@
...
+            } else {
+                final String[] dsParts = token.substring(i + 1).split("\\+");
+                if (dsParts.length != 2) {
+                    throw new IllegalArgumentException(
+                            "Malformed datastream token: " + token);
+                }
+                try {
+                    final String encodedToken = token.substring(0, i) + "/" + uriEncode(dsParts[0]) + "/" + uriEncode(
+                            dsParts[1]);
+                    if (token.startsWith(FEDORA_URI)) {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: I'd prefer a `?:` here instead of a `if-else`.

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java (hunk 6 above)
Comment (ajs6f) [reply src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: Also, I'd prefer a `?:` here instead of a `if-else`.

**Review by ajs6f — CHANGES_REQUESTED** [review]
I guess I'm okay with this. I would still like to have a better understanding of what the presence of absence of `info:fedora/` is all about.

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java (hunk 6 above)
Comment (whikloj) [reply src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: I tried creating a new object with a  new Fedora 3.8.1 repo and adding a datastream (all using the Flash admin tool) and it does not persist the "info:fedora/" prefix when referencing any managed datastreams. Only thing I can think is
```
<foxml:contentLocation TYPE="INTERNAL_ID" REF="uofm:2553586+OBJ+OBJ.0"/>
```
are there other `TYPE`s that might use the `info:fedora/` prefix?

**Comment by whikloj** [comment]
If I move this into the `ObjectProcessor` it could be `private` methods, but then I am unsure how to test it?

File: src/main/java/edu/si/fcrepo/ObjectProcessor.java [hunk 8]
```diff
@@ -142,11 +150,14 @@ public void accept(final URI objectId) {
                 final FedoraObject object = foxmlReader.readObject(objectBits);
                 foxmlReader.close();
                 // constant per-resource triples
-                for (final Triple t : constantObjectTriples(object, createURI("info:fedora/" + object.pid())))
+                for (final Triple t : constantObjectTriples(object, createURI("info:fedora/" + object.pid()))) {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/ObjectProcessor.java]: This looks like your IDE added braces where they aren't needed?

File: src/main/java/edu/si/fcrepo/ObjectProcessor.java [hunk 9]
```diff
@@ -156,8 +167,9 @@ public void accept(final URI objectId) {
                     final SAXParser parser = saxFactory.newSAXParser();
                     parser.parse(dcXML, new DublinCoreContentHandler(tripleSink, createURI(objectId.toString())));
                 });
-                if (relsIntDatastream != null)
+                if (relsIntDatastream != null) {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/ObjectProcessor.java]: No more braces!

File: src/main/java/edu/si/fcrepo/ObjectProcessor.java [hunk 10]
```diff
@@ -247,7 +259,9 @@ private InputStream getDatastreamContent(final Datastream datastream) throws IOE
      */
     private static Triple[] constantDatastreamTriples(final String objectUri, final Datastream ds) {
         final String dsId = ds.id();
-        if (dsId.equals("AUDIT")) return new Triple[0];
+        if (dsId.equals("AUDIT")) {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/ObjectProcessor.java]: No braces, no new lines!

File: src/main/java/edu/si/fcrepo/ObjectProcessor.java [hunk 11]
```diff
@@ -275,4 +289,64 @@ default void close() {/* NO OP */}
...
         tripleSink.close();
     }
+
+    /**
+     * Converts a token to a token-as-blobId.
+     *
+     * @param token the token to convert
+     * @return the AkubraLowLevelStorage BlobId
+     */
+    public static URI getBlobId(final URI token) {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/ObjectProcessor.java]: Does this need to be `public` now that it is in `ObjectProcessor`?

File: src/main/java/edu/si/fcrepo/ObjectProcessor.java [hunk 12]
```diff
@@ -275,4 +289,64 @@ default void close() {/* NO OP */}
...
+     * Object tokens are simply prepended with <code>info:fedora/</code>, whereas datastream tokens are additionally
+     * converted such that <code>ns:id+dsId+dsVersionId</code> becomes
+     * <code>info:fedora/ns:id/dsId/dsVersionId</code>, with the dsId and dsVersionId segments URI-percent-encoded
+     * with UTF-8 character encoding.
+     *
+     * @param token the token to convert.
+     * @return the blob id.
+     * @throws IllegalArgumentException if the token is not a well-formed pid or datastream token.
+     */
+    public static URI getBlobId(final String token) {
```
Comment (ajs6f) [inline src/main/java/edu/si/fcrepo/ObjectProcessor.java]: Does this need to be `public` now that it is in `ObjectProcessor`?

**Review by ajs6f — APPROVED** [review]
I will merge this as-is, if you need me to, because it's good, but if you have the time, there are some formatting changes here that I don't really want, so if you could back those out, it would be ideal.

**Comment by ajs6f** [comment]
> If I move this into the ObjectProcessor it could be private methods, but then I am unsure how to test it?

Oh, didn't see this! Yeah, that's more annoying. Well, at least package-private, okay?

File: src/main/java/edu/si/fcrepo/AkubraIDConverter.java (hunk 6 above)
Comment (ajs6f) [reply src/main/java/edu/si/fcrepo/AkubraIDConverter.java]: The [only other value](https://www.duraspace.org/archive/fedora/definitions/1/0/foxml1-1.xsd) there is `URL`. Well, I'm not going to worry a whole lot more about it. If it works for you, that's what matters.

File: src/main/java/edu/si/fcrepo/ObjectProcessor.java (hunk 9 above)
Comment (whikloj) [reply src/main/java/edu/si/fcrepo/ObjectProcessor.java]: How do I turn this off in Eclipse. I set up new formatting rules and everything but it keeps adding them. 😠

Comment (ajs6f) [reply src/main/java/edu/si/fcrepo/ObjectProcessor.java]: Are you using the `Format` command? That's what will trigger the rules. But don't worry about it a lot, if it's not obvious we'll merge and I'll fiddle with it later.

**Comment by ajs6f** [comment]
Merging this mother...
